name: '自动测试代码是否正确，与题解对拍'

on:
  push:
    branches: [main] # 根据你的需求修改分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm i

      - name: Run lint
        run: |
          pnpm lint

      - name: Run tests
        run: |
          pnpm test
